import type { Metadata } from "next";
import { Exo, Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import AuthProvider from "@/context/auth-provider";
import CartContextProvider from "@/context/cart-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const exo = Exo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Rootlayout {
  children : React.ReactNode
}

export default function RootLayout({children}: Readonly<Rootlayout>) 
{
  return (
    <html lang="en" className={cn("h-full", "antialiased", exo.className, "font-sans", inter.variable)} suppressHydrationWarning>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthProvider>
          <CartContextProvider>

            <Navbar/>
            {children}
            <Toaster position="top-right" richColors/>
            <Footer/>
          
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
