import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const exo = Exo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Rootlayout {
  children : React.ReactNode
}

export default function RootLayout({children}: Readonly<Rootlayout>) 
{
  return (
    <html lang="en" className={`${exo.className} h-full antialiased`} suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
